project:
  type: book
  output-dir: docs
  resources: images/_icons/

book:
  title: "Introducción a GitHub para Investigador(a|e)s"
  author: "Beatriz Milz y Yanina Bellini Saibene"
  doi: TBD
  language: "ES"
  repo-url: "https://github.com/Git4Researchers/LatinR2024Workshop"
  chapters:
    - text: "Informacion del taller"
      href: index.qmd
    - text: "Introduccion"
      href: intro.qmd
    - text: "Perfil en GitHub"
      href: profile.qmd
    - text: "Trabajando con repositorios"
      href: repositories.qmd
    - text: "Nuestra lista TODO con Issues"
      href: issues.qmd
    - text: "Ordenando nuestro trabajo"
      href: projects.qmd
    - text: "Trabajando con otras personas"
      href: collaboration.qmd
    - text: "Compartir y mantener la autoria"
      href: release.qmd
  appendices:
    - text: "Instalando el entorno de trabajo"
      href: A_instalacion.qmd
  sidebar:
    background: "#275f8a"
    search: true

format:
  html:
    theme:
      light: [cosmo, style.scss]
    code-link: true
    mainfont: Noto Sans
    monofont: Source Code Pro
    author-meta: "Beatriz Milz y Yanina Bellini Saibene"
  # pdf:
  #   documentclass: scrreprt

lang: es

