project:
  type: book
  output-dir: docs
  resources: images/_icons/

book:
  title: "Introducción a GitHub para Investigador(a|e)s"
  author: "Beatriz Milz y Yanina Bellini Saibene"
  doi: TBD
  language: "ES"
  repo-url: "https://github.com/Git4Researchers/LatinR2024Workshop"
  chapters:
    - index.qmd
  appendices:
    - A_instalacion.qmd
  sidebar:
    background: "#275f8a"
    search: true

format:
  html:
    theme:
      light: [cosmo, style.scss]
    code-link: true
    mainfont: Noto Sans
    monofont: Source Code Pro
    author-meta: "Beatriz Milz y Yanina Bellini Saibene"
  pdf:
    documentclass: scrreprt



